### ISSUE TITLE
Incompatible decimalChar in table schema and csv data files

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#1005]
# Overview

If a field has a period (`.`) as a decimal char in the table schema but the actual csv file uses comma (`,`), a `type-error` is reported in `frictionless validate`. 

However, if the situation is reversed (comma in table schema but period in csv) no error is reported and `1.234` will be interpreted as `Decimal('1.234')`, which might not be the case in the actual data (eg. because of a missing `groupChar`).

Shouldn't an error be reported in both cases? Here is an reproducible example for the schema

```json
"fields": [
  {
    "name": "PERIOD_DECIMAL_CHAR",
    "type": "number",
    "decimalChar": "."
  },
  {
    "name": "COMMA_DECIMAL_CHAR",
    "type": "number",
    "decimalChar": ","
  }
]
```

and data

```
PERIOD_DECIMAL_CHAR;COMMA_DECIMAL_CHAR
5,678;1.234
```

```python
>>> from frictionless import Package, validate_resource
>>> dp = Package('https://raw.githubusercontent.com/dados-mg/datapackage-reprex/invalid-decimal-char/datapackage.json')
>>> resource = dp.get_resource('resource')
>>> report = validate_resource(resource)
>>> rows = resource.read_rows()
>>> report.flatten(["rowPosition", "fieldPosition", "code", "message"])
[[2, 
1, 
'type-error', 
'Type error in the cell "5,678" in row "2" and field "PERIOD_DECIMAL_CHAR" at position "1": type is "number/default"']]
>>> rows[0]
{'PERIOD_DECIMAL_CHAR': None, 'COMMA_DECIMAL_CHAR': Decimal('1.234')}
```

**Comment by roll** [comment]
Thanks @fjuniorr, it looks like a bug. @aivuk can you please take a look

**Comment by aivuk** [comment]
@roll I think the problem is happening because how we are using the dechimalChar information. At https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/types/number.py#L58 we just use it to substitute the decimalChar for a '.' and then we parse the string to a float number. If the decimalChar specified is a ',' and the number is written with dot, the replacement will not do anything and the parse of the number will just works. One approach for solving that is checking using a regular expression and using the decimalChar in it to validate the number before parsing it. What do you think?

**Comment by roll** [comment]
@aivuk 
It's hard to wrap my head out it quickly. Can you please try PRing a fix. I think one thing we need to take into account is that we need to keep high performance on number parsing so if we can use some smart regex alternative (like split) it will be better

**Comment by aivuk** [comment]
@roll you can see my pull request at https://github.com/frictionlessdata/frictionless-py/pull/1032 but I think the solution is a bit hackish and it will fail in the rare case where someone uses a "|" as a decimal character separator.

**Comment by roll** [comment]
Thanks @aivuk! I'll review it

**Comment by roll** [comment]
@aivuk 
I'm thinking about something like this:

```python
            def processor(cell):
                cell = cell.replace(self.field.group_char, "")
                cell = cell.replace(self.field.decimal_char, ".")
                # But we also need to cover "bareNumber" case
                if self.field.decimal_char != '.' and '.' in cell:
                    return None
                if self.read_cell_pattern:
                    cell = self.read_cell_pattern.sub("", cell)
                return cell

```

**Comment by aivuk** [comment]
That's not going to work. If the decimal_char is a comma (',') it's going to be replaced by a '.' at `cell = cell.replace(self.field.decimal_char, ".")` and then fail in the next step.

**Comment by aivuk** [comment]
Other solution that I can see is playing with the locale, setting the decimal character on it, because this is what Python uses behind the scenes to parse a string to a float. But this will probably not be the best performance solution.

**Comment by roll** [comment]
What if we check it before the first replacement? Anyway let's start with tests and see what we can do. I wouldn't touch locale as the `processor` function might be called million times per validation including (maybe in-parallel). We also probably need to return different `processor` functions depending on the case to keep the current performance for common cases over edge cases.

**Comment by aivuk** [comment]
@roll Investigating this further I think that maybe it's a good idea to ad a faster parser for the string to numerical types conversion. I went to a rabbit hole where I went deep on how Python do the conversion:

 * https://github.com/python/cpython/blob/e349bf23584eef20e0d1e1b2989d9b1430f15507/Python/dtoa.c#L1434

And saw that there is no way to change the decimal separator because it's hardcoded to '.' (https://github.com/python/cpython/blob/e349bf23584eef20e0d1e1b2989d9b1430f15507/Python/dtoa.c#L1479)

A simpler way to approach the problem could be using libraries like [fastnumbers](https://github.com/SethMMorton/fastnumbers), a really small library but with good benchmarks (see https://github.com/SethMMorton/fastnumbers#timing in the benchmarks there is also a regular expression that could be adapted to check if a number is written in the right format according to the datapackage).

Numpy also has a fast parser, but I think adding it as a dependency would be too much.

There is also this option in C++ https://lemire.me/blog/2020/03/10/fast-float-parsing-in-practice/ (the source code is here https://github.com/lemire/fast_double_parser) and we could create a library to use it with python.

**Comment by roll** [comment]
@aivuk 
`fastnumbers` looks promising for this issue

I'm curious if we can find something similar for date/times also
