### ISSUE TITLE
BUG in validate --parallel because of trusted feature

### ISSUE THREAD

**Issue by paulgirard** [frictionlessdata/frictionless-py#1043]
# Overview
Try to validate a datapackage in parallel mode with recent version throws a python error:
```json
 {
      "code": "task-error",
      "name": "Task Error",
      "tags": [],
      "note": "__init__() got an unexpected keyword argument 'trusted'",
      "message": "The task has an error: __init__() got an unexpected keyword argument 'trusted'",
      "description": "General task-level error."
    }
```
# Workaround

Removing the --parallel option removes the error.

# Context 
Here is the commit where I removed the --parallel option https://github.com/medialab/toflit18_data/commit/3c317ff80cf45c1b0d5fd984bac1f393f8f4b8e5

**Comment by roll** [comment]
Thanks @paulgirard!

We will investigate and fix it

**Comment by lwinfree** [comment]
@roll look at the notes in Slack - thx

**Comment by roll** [comment]
@shashigharti 
What steps did you use to reproduce the error?

**Comment by shashigharti** [comment]
@roll 

**Running this command:**
`frictionless  validate --json  --limit-errors 5000 --type package ../datapackage.json > datapackage_validation.json`

**file**: https://github.com/medialab/toflit18_data/blob/master/scripts/datapackage_validation.json

**Comment by roll** [comment]
Hi @paulgirard,

The `datapackage.json` has a mistake -  `classifications_index` declares `fields` on the `resource` level instead of providing it as a part of `schema` - `resource -> schema -> fields`.

We're going to enable validation hints to help with situations like this - https://github.com/frictionlessdata/frictionless-py/issues/993

Also, I'm reviewing the validation flow to improve the error messages.
