### ISSUE TITLE
Compressed multipart resource doesn't work

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1215]
# Overview

See this failing test:

```
def test_multipart_loader_with_compressed_parts():
    with Resource(
        path="data/chunk1.csv.zip", extrapaths=["data/chunk2.csv.zip"]
    ) as resource:
        assert resource.innerpath == ""
        assert resource.compression == ""
        assert resource.header == ["id", "name"]
        assert resource.read_rows() == [
            {"id": 1, "name": "english"},
            {"id": 2, "name": "中国人"},
        ]

```

**Comment by shashigharti** [comment]
@roll I found out the following:

1. error occurs due to the following reason, In multipart loader `MultipartByteStream`, seek function has one param only but it requires two([link](https://github.com/python/cpython/blob/3.11/Lib/zipfile.py#L292)):`offset and whence `
And `seek` function also should accept negative value ([link](https://github.com/python/cpython/blob/3.11/Lib/zipfile.py#L299))
2. It also requires `tell` function that will return the size of the file ([link](https://github.com/python/cpython/blob/3.11/Lib/zipfile.py#L293)).

I am looking for your suggestion and feedback on it, if my analysis is in the correct path.

Thank you for your time!
