### ISSUE TITLE
Recover steps.table_pivot

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1220]
# Overview

See this failing test:

```
def test_step_table_pivot():
    source = Resource("data/transform-pivot.csv")
    pipeline = Pipeline(
        steps=[
            steps.table_normalize(),
            steps.table_pivot(f1="region", f2="gender", f3="units", aggfun=sum),
        ],
    )
    target = source.transform(pipeline)
    assert target.schema.to_descriptor() == {
        "fields": [
            {"name": "region", "type": "string"},
            {"name": "boy", "type": "integer"},
            {"name": "girl", "type": "integer"},
        ]
    }
    assert target.read_rows() == [
        {"region": "east", "boy": 33, "girl": 29},
        {"region": "west", "boy": 35, "girl": 23},
    ]
```

**Comment by shashigharti** [comment]
@roll `resource.infer()` does not reset all the metadata and schema such as:
`resource.schema, '_TableResource__header' and '_TableResource__buffer' `

Due to that when we read rows and schema it returns the original data not the modified one.
`target.read_rows()`
`target.schema.to_descriptor()`

Example data after `resource.infer()`
`resource.__dict__`
`{......., '_TableResource__buffer': b'region,gender,style,units\neast,boy,tee,12\neast,boy,golf,14\neast,boy,fancy,7\neast,girl,tee,3\neast,girl,golf,8\neast,girl,fancy,18\nwest,boy,tee,12\nwest,boy,golf,15\nwest,boy,fancy,8\nwest,girl,tee,6\nwest,girl,golf,16\nwest,girl,fancy,1\n', '_TableResource__sample': [('region', 'boy', 'girl'), ('east', 33, 29), ('west', 35, 23)], '_TableResource__labels': ['region', 'boy', 'girl'], '_TableResource__fragment': [('east', 33, 29), ('west', 35, 23)], '_TableResource__header': ['region', 'gender', 'style', 'units']...}`

only `_TableResource__sample` , `_TableResource__labels` and `_TableResource__fragment` are updated.

I request for your feedback. Thank you!

**Comment by roll** [comment]
Thanks @shashigharti ! I'll investigate

**Comment by roll** [comment]
Thanks @shashigharti! I reset `schema` here - https://github.com/frictionlessdata/framework/pull/1545

**Comment by shashigharti** [comment]
Thanks!
