### ISSUE TITLE
Infer fails to detect the correct schema for XLSX

### ISSUE THREAD

**Issue by aivuk** [frictionlessdata/frictionless-py#1343]
@roll Trying to infer the schema for http://coronavirus.saude.mg.gov.br/images/microdados/xlsx_sistemas.xlsx:

```
from frictionless import Resource
r = Resource('xlsx_sistemas.xlsx')
r.infer()
r.schema
```
Schema:
```
{'fields': [{'name': 'ID', 'type': 'any'}]}
```

---

Update:

Currently, `XlsxParser` it not able to read this file properly: `sheet.iter_rows()` just returns first cell and exits. We need to review the way we use `openpyxl` streaming/etc-wise

**Comment by aivuk** [comment]
I converted the file above to csv using pandas and ran the same code above for the csv:
```
from frictionless import Resource
r = Resource('xlsx_sistemas.csv')
r.infer()
r.schema
```
the schema was correctly infered:
```
{'fields': [{'name': 'field1', 'type': 'integer'},
            {'name': 'ID', 'type': 'integer'},
            {'name': 'URS', 'type': 'string'},
            {'name': 'MICRO', 'type': 'string'},
            {'name': 'MACRO', 'type': 'string'},
            {'name': 'DATA_NOTIFICACAO', 'type': 'string'},
            {'name': 'CLASSIFICACAO_CASO', 'type': 'string'},
            {'name': 'SEXO', 'type': 'string'},
            {'name': 'IDADE', 'type': 'number'},
            {'name': 'FAIXA_ETARIA', 'type': 'string'},
            {'name': 'MUNICIPIO_RESIDENCIA', 'type': 'string'},
            {'name': 'CODIGO', 'type': 'number'},
            {'name': 'EVOLUCAO', 'type': 'string'},
            {'name': 'DATA_EVOLUCAO', 'type': 'string'},
            {'name': 'DATA_1_SINTOMA', 'type': 'any'},
            {'name': 'INTERNACAO', 'type': 'string'},
            {'name': 'UTI', 'type': 'string'},
            {'name': 'RACA', 'type': 'string'},
            {'name': 'ETNIA', 'type': 'any'},
            {'name': 'COMORBIDADE', 'type': 'string'},
            {'name': 'DATA_ATUALIZACAO', 'type': 'string'},
            {'name': 'ORIGEM_DA_INFORMACAO', 'type': 'string'}]}
```

**Comment by shashigharti** [comment]
Hi @roll @aivuk , I opened this file using 'libre office' and saved it again then the 'infer' worked. And it seems to be due to this reason:
[link]( https://openpyxl.readthedocs.io/en/latest/optimized.html#worksheet-dimensions) , some applications not setting dimensions correctly.

The solution is using:
```
if "A1:A1" == sheet.calculate_dimension():
   sheet.reset_dimensions()
```

Should I apply this fix or what do you suggest? Thank you!

**Comment by shashigharti** [comment]
This happens because some applications do not set dimensions correctly and due to that the fields are not inferred. [link](https://openpyxl.readthedocs.io/en/latest/optimized.html#worksheet-dimensions)

This can be solved by opening the file in another application (Microsoft excel, libre office etc) and retry.
