### ISSUE TITLE
ModuleNotFoundError: No module named 'attrs'

### ISSUE THREAD

**Issue by JBPressac** [frictionlessdata/frictionless-py#1353]
Hello,

Using frictionless==5.0.0b22 + Python 3.9.5 , the following Python code generates a `ModuleNotFoundError: No module named 'attrs'` error:

```
from frictionless import Detector, describe

detector = Detector(field_missing_values=["", "n/a"])
```

Thank you,

**Comment by shashigharti** [comment]
Hi @JBPressac, Thanks for reporting!

It seems to be working(screenshot attached). Can you please confirm if the python version >=3.5 on your end.
![attrserror](https://user-images.githubusercontent.com/5582809/208843434-0179a865-6ba2-48eb-a715-8f8ee473bc8f.png)

**Comment by shashigharti** [comment]
Closing for now. Please let us know if you need additional help.

**Comment by chris48s** [comment]
I hit this issue too. It happens because `import attrs` was introduced in `attrs==21.3.0` (see https://www.attrs.org/en/stable/changelog.html#id7 ) but frictionless requires `attrs>=21.0` so depending on what else is in your virtualenv/lockfile an incompatible version (requiring `import attr`) may be resolved. I've submitted a quick PR over at #1392 bumping the minimum required version in `setup.py`
