### ISSUE TITLE
`frictionless query` results in error for multipart resource

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#1477]
```shell
frictionless query https://zenodo.org/record/5653311
───────────────────────────────────────────────────────────── Index ─────────────────────────────────────────────────────────────
[reference-data] Indexed 1954 bytes in 2.697 seconds
[gps] errored
[acceleration] errored
```

The above Zenodo deposit (https://zenodo.org/record/5653311) consists of 3 resources:

- `reference-data`: works fine, small and consists of a single unzipped file.
- `gps`: does not work, are bigger and consists of an array of gz files. **See below, cause seems to be an array of files**

**Comment by peterdesmet** [comment]
Tried with another dataset where files are not split, and there it works:

```
frictionless query https://zenodo.org/record/6599273
```

The issue is thus related to a resource that consists of an array of files.

**Comment by roll** [comment]
Thanks!

**Comment by shashigharti** [comment]
@roll, I tested in my system and it works for both resources(screenshot2). Could it be due to resource limit? I tried in virtual machine and it did not work for all (screenshot1)

screenshot1
![screenshot2](https://github.com/frictionlessdata/framework/assets/5582809/9a1a5cbd-fbd1-42b4-962d-ec20871f0728)

screenshot2
![screenshot1](https://github.com/frictionlessdata/framework/assets/5582809/6366c6a2-c134-40e7-a38e-6c7d0b73e9af)

Thank you!

**Comment by shashigharti** [comment]
With frictionless `version 5.15.4` it works fine in windows as well. 

![Image](https://github.com/frictionlessdata/frictionless-py/assets/5582809/f16659cc-aaf4-4f5d-9bc4-3e2ff17e3c51)

**Comment by shashigharti** [comment]
It is working in both windows and linux. Closing this issue, if you need help let us know.
