### ISSUE TITLE
Ability to validate a zipped data package

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1499]
# Overview

```
frictionless validate datapackage.zip
```

**Comment by shashigharti** [comment]
@roll, [here](https://github.com/frictionlessdata/framework/blob/main/frictionless/resource/factory.py#L28) the correct adapter is not selected which is `ZipPlugin` and package is not read. Because `packagify` variable is not set to true when read from Resource returned [here](https://github.com/frictionlessdata/framework/blob/main/frictionless/formats/zip/plugin.py#L27)

I need your suggestion to proceed. Thank you!
