### ISSUE TITLE
Ability to pass dialect parameters via CLI commands

### ISSUE THREAD

**Issue by sirex** [frictionlessdata/frictionless-py#731]
# Overview

Is it possible to provide dialect options via command line?

For example:

    frictionless extract --sheet Sheet2 data.ods

I see, that ODS dialect does support `sheet` parameter, but could not find how to pass it via command line.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi,

It's not yet supported I've marked it as a feature request

**Comment by alexkreidler** [comment]
Want to mention that this is possible by passing the dialect parameters via JSON like so, and I've tested this works on an example ODS spreadsheet with two sheets: 
```
frictionless extract --dialect '{"sheet": "Sheet2"}' ~/Documents/example.ods
```
because of this line:
https://github.com/frictionlessdata/frictionless-py/blob/0ce096c9b122cabe7f2c3feeabe7d48664712776/frictionless/program/extract.py#L83-L83

We could either update the CLI help/docs to mention this is possible, or I could investigate parsing the dialect options to expose them as CLI options like @sirex showed.

@roll Thoughts on this?

**Comment by roll** [comment]
@sirex 
@alexkreidler 
Yes, I've implemented general support for Controls and Dialects provided as a JSON to CLI. It makes sense because Frictionless is pluggable and, generally speaking, we can't predict what dialect options are available for some installation as it can use custom plugins.

On the other hand, I think we can provide popular shortcuts like `sheet` (excel, ods), `table` (sql, others?), and etc?

So if @alexkreidler you like this issue to work on I would suggest the following plan:
- update CLI documentation when it's needed adding that users can pass `--control` and `--dialect` as JSON
- find 3-5 common dialect options that we can provide directly like `--sheet`
- ensure that it doesn't clash with other CLI options
- implement their support

WDYT?

**Comment by alexkreidler** [comment]
Yeah I can definitely do that.

There might be a way to get the [attributes from an object](https://stackoverflow.com/questions/2675028/list-attributes-of-an-object) (e.g.  `Dialect`) with `dir()` or something else, but then turning the attributes into meaningful options, integrating them with the CLI library dynamically, and making sure they don't clash would be a bit more involved.

I'll go ahead with your approach.

**Comment by roll** [comment]
> There might be a way to get the attributes from an object (e.g. Dialect) with dir() or something else, but then turning the attributes into meaningful options, integrating them with the CLI library dynamically, and making sure they don't clash would be a bit more involved.

Good idea. Although we might then need to filter data types not possible to stringify (like HTTP Request class `plugins.remote.RemoteControl`) and friend it with `Typer` commands. Also, loading all of them before the CLI run might slightly slower the program. I think it makes sense to start from the more simple version and then try to prototype this more sophisticated one.

**Comment by roll** [comment]
Hi @aivuk,

can you please take a look if we can finish this one?
