### ISSUE TITLE
Error validating inline data resource

### ISSUE THREAD

**Issue by henhuy** [frictionlessdata/frictionless-py#746]
# Overview

I'm trying to validate a resource with inline data in tabular data format, but report always shows error:
`The data resource has an error: "{'data': [{'id': 1, 'scenario': 'base', 'region': {'DE': ['BB', 'BE', 'BW']}, 'year': 2016, 'source': 'test', 'comment': 'comment'}], 'profile': 'tabular-data-resource', 'schema': {'fields': [{'name': 'id', 'type': 'integer'}, {'name': 'scenario', 'type': 'string'}, {'name': 'region', 'type': 'object'}, {'name': 'year', 'type': 'integer'}, {'name': 'source', 'type': 'string'}, {'name': 'comment', 'type': 'string'}], 'primaryKey': ['id']}} is not valid under any of the given schemas" at "" in metadata and at "oneOf" in profile`
which is not very helpful?!
Minimal example code:
```
data = [
    {
        "id": 1,
        "scenario": "base",
        "region": {
            "DE": [
                "BB",
                "BE",
                "BW",
            ]
        },
        "year": 2016,
        "source": "test",
        "comment": "comment",
    }
]
schema = {
    "fields": [
        {"name": "id", "type": "integer"},
        {"name": "scenario", "type": "string"},
        {"name": "region", "type": "object"},
        {"name": "year", "type": "integer"},
        {"name": "source", "type": "string"},
        {"name": "comment", "type": "string"},
    ],
    "primaryKey": ["id"],
}
resource = Resource(
    profile="tabular-data-resource", data=data, schema=schema
)
validate_resource(resource, original=True)
```

Help would be much appreciated! thx in advance

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @henhuy,

Because you use the `original` argument it doesn't infer a resource name. To make it work you just need to provide a resource's name to the `Resource` constructor.

Currently, the error message is not helpful at all as we use an official JSON Schema - https://specs.frictionlessdata.io/schemas/tabular-data-package.json

We have an issue for it - https://github.com/frictionlessdata/frictionless-py/issues/239

Please re-open if needed
