### ISSUE TITLE
Implement package/resource/schema.to_markdown

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#837]
# Overview

> https://framework.frictionlessdata.io/docs/guides/describing-data

In Frictionless Framework a user can instantiate a Schema, Resource, and Package objects. All of them are Metadata objects which is a Python dictionary with some additional functionality. 

For example, all these classes have `metadata.to_yaml` that converts the metadata that a package/resource/schema has to a YAML string or file.

Users are interested in having `package/resource/schema.to_markdown` function that will convert metadata to a MD string or file. It might be useful for composing readmes on github etc. See https://github.com/frictionlessdata/project/discussions/665

# Plan

- [ ] Review an [existing external lib](https://github.com/geoffreyaldebert/table-schema-to-markdown) for reference (not sure we can re-use this code)
- [ ] Decide on the way of composing markdown text: using some markdown composer, Jinja template or native Python strings (the latter might be messy) ping @roll to sync
- [ ] Decide on what should be a Markdown output. For example, this one for a Table Schema - https://github.com/geoffreyaldebert/table-schema-to-markdown/blob/master/tests/files/expected_repertoire.md. And this one - https://datahub.io/core/co2-ppm - is a package presentation (of course we can't have interactive parts) ping @roll to sync
- [ ] Prototype all the functions
- [ ] Implement all the functions adding docstrings
- [ ] Write functional tests

**Comment by ezwelty** [comment]
As another style example, the readme for https://gitlab.com/wgms/glathida is generated automatically from `datapackage.json` (with a funky bespoke R script that I will probably need to rewrite in python). Only to say that a markdown representation can take many shapes, so a templating system seems important.

**Comment by roll** [comment]
The work is started here - https://github.com/frictionlessdata/frictionless-py/pull/897. It uses Handlebars template engine which I think is better to replace by Pythonic Jinja. This code can be used as a starting point though

**Comment by ezwelty** [comment]
I have played around with using `jinja` to achieve this functionality. Basically, I create a custom jinja environment for template rendering that follows relative paths in nested templates and a few useful custom filters that can be used within the templates.

```py
from typing import List, Union
import jinja2


# ---- Custom filters ----

def filter_dict(
    x: dict, include: list = None, exclude: list = None, order: list = None
) -> dict:
    """Filter and order dictionary by key names."""
    if include:
        x = {key: x[key] for key in x if key in include}
    if exclude:
        x = {key: x[key] for key in x if key not in exclude}
    if order:
        index = [
            (order.index(key) if key in order else len(order), i)
            for i, key in enumerate(x)
        ]
        sorted_keys = [key for _, key in sorted(zip(index, x.keys()))]
        x = {key: x[key] for key in sorted_keys}
    return x


def dicts_to_markdown_table(dicts: List[dict], **kwargs) -> str:
    """Tabulate dictionaries and render as a Markdown table."""
    if kwargs:
        dicts = [filter_dict(x, **kwargs) for x in dicts]
    df = pd.DataFrame(dicts)
    return df.where(df.notnull(), None).to_markdown(index=False)


def json_to_markdown(
    x: Union[dict, list, int, float, str, bool],
    level: int = 0,
    tab: int = 2,
    flatten_scalar_lists: bool = True,
) -> str:
    """Render any JSON-like object as Markdown, using nested bulleted lists."""
    def _scalar_list(x) -> bool:
        return isinstance(x, list) and all(not isinstance(xi, (dict, list)) for xi in x)

    def _iter(x: Union[dict, list, int, float, str, bool], level: int = 0) -> str:
        if isinstance(x, (dict, list)):
            if isinstance(x, dict):
                labels = [f"- `{key}`" for key in x]
            elif isinstance(x, list):
                labels = [f"- [{i + 1}]" for i in range(len(x))]
            values = x if isinstance(x, list) else list(x.values())
            if isinstance(x, list) and flatten_scalar_lists:
                scalar = [not isinstance(value, (dict, list)) for value in values]
                if all(scalar):
                    values = [f"{values}"]
            lines = []
            for label, value in zip(labels, values):
                if isinstance(value, (dict, list)) and (
                    not flatten_scalar_lists or not _scalar_list(value)
                ):
                    lines.append(f"{label}\n{_iter(value, level=level + 1)}")
                else:
                    lines.append(f"{label} {value}")
            txt = "\n".join(lines)
        else:
            txt = str(x)
        if level > 0:
            txt = jinja2.filters.do_indent(txt, width=tab, first=True, blank=False)
        return txt

    return jinja2.filters.do_indent(
        _iter(x, level=0), width=tab * level, first=True, blank=False
    )


# ---- Custom Jinja environment ----

class RelativeEnvironment(jinja2.Environment):
    """Override join_path() to enable relative template paths."""

    def join_path(self, template, parent):
        return os.path.normpath(os.path.join(os.path.dirname(parent), template))


JINJA_ENVIRONMENT = RelativeEnvironment(
    loader=jinja2.FileSystemLoader("."), lstrip_blocks=True, trim_blocks=True
)
JINJA_ENVIRONMENT.filters["filter_dict"] = filter_dict
JINJA_ENVIRONMENT.filters["dict_to_markdown"] = json_to_markdown
JINJA_ENVIRONMENT.filters["tabulate"] = dicts_to_markdown_table


def render_template(path: str, data: dict) -> str:
    template = JINJA_ENVIRONMENT.get_template(path)
    return template.render(**data)
```

Say we have the following data package descriptor:

```py
descriptor = {'name': 'package',
 'resources': [{'name': 'main',
   'schema': {'fields': [{'name': 'id',
      'description': 'Any positive integer',
      'type': 'integer',
      'constraints': {'minimum': 1}},
     {'name': 'integer_minmax',
      'description': 'An integer between 1 and 10',
      'type': 'integer',
      'constraints': {'minimum': 1, 'maximum': 10}},
     {'name': 'number_min',
      'description': 'Any number >= 0',
      'type': 'number',
      'constraints': {'minimum': 0}},
     {'name': 'boolean', 'description': 'Any boolean', 'type': 'boolean'},
     {'name': 'string_minmax',
      'description': 'Any string with length between 2 and 3',
      'type': 'string',
      'constraints': {'minLength': 2, 'maxLength': 3}},
     {'name': 'string_enum',
      'description': 'One of the first three letters of the alphabet',
      'type': 'string',
      'constraints': {'enum': ['a', 'b', 'c']}}],
    'primaryKey': ['id']}},
  {'name': 'secondary',
   'schema': {'fields': [{'name': 'main_id',
      'description': 'Any value in main.id',
      'type': 'integer'},
     {'name': 'string',
      'description': 'Any string of up to 3 characters',
      'type': 'string',
      'constraints': {'maxLength': 3}}],
    'foreignKeys': [{'fields': ['main_id'],
      'reference': {'resource': 'main', 'fields': ['id']}}]}}]}
```

### Generic rendering with `json_to_markdown`

We can convert it to markdown using the generic `json_to_markdown()` function:

```py
json_to_markdown(descriptor)
```

- `name` package
- `resources`
  - [1]
    - `name` main
    - `schema`
      - `fields`
        - [1]
          - `name` id
          - `description` Any positive integer
          - `type` integer
          - `constraints`
            - `minimum` 1
        - [2]
          - `name` integer_minmax
          - `description` An integer between 1 and 10
          - `type` integer
          - `constraints`
            - `minimum` 1
            - `maximum` 10
        - [3]
          - `name` number_min
          - `description` Any number >= 0
          - `type` number
          - `constraints`
            - `minimum` 0
        - [4]
          - `name` boolean
          - `description` Any boolean
          - `type` boolean
        - [5]
          - `name` string_minmax
          - `description` Any string with length between 2 and 3
          - `type` string
          - `constraints`
            - `minLength` 2
            - `maxLength` 3
        - [6]
          - `name` string_enum
          - `description` One of the first three letters of the alphabet
          - `type` string
          - `constraints`
            - `enum` ['a', 'b', 'c']
      - `primaryKey` ['id']
  - [2]
    - `name` secondary
    - `schema`
      - `fields`
        - [1]
          - `name` main_id
          - `description` Any value in main.id
          - `type` integer
        - [2]
          - `name` string
          - `description` Any string of up to 3 characters
          - `type` string
          - `constraints`
            - `maxLength` 3
      - `foreignKeys`
        - [1]
          - `fields` ['main_id']
          - `reference`
            - `resource` main
            - `fields` ['id']
           
### Jinja templates

Alternatively, we can have one (or multiple nested) Jinja templates for our classes. Below, I define one template for package, resource, and field. Note how I use the filters defined above.

`package.md`

```jinja
# `{{ package.name }}`{% if package.title %} {{ package.title }}{% endif %}

{{ package | filter_dict(exclude=['name', 'title', 'resources', 'contributor']) | dict_to_markdown() }}

{% for resource in package.resources %}
  {% include 'resource.md' %}

{% endfor %}
```

`resource.md`

```jinja
## `{{ resource.name }}`{% if resource.title %} {{ resource.title }}{% endif %}
{{ '\n' }}
{% if resource.description %}
  - `description` {{ resource.description | indent(4, False) }}
{% endif %}
{% if resource.path %}
  - `path` {{ resource.path }}
{% endif %}
{% if resource.schema %}
  - `schema`
{{ resource.schema | filter_dict(exclude=['fields']) | dict_to_markdown(level=2) }}
{% endif %}

{% for field in resource.schema.fields %}
  {% include 'field.md' %}

{% endfor %}
```

`field.md`

```jinja
### `{{ field.name }}`{% if field.title %} {{ field.title }}{% endif %}
{{ '\n' }}
{% if field.description %}
  - `description` {{ field.description | indent(4, False) }}
{% endif %}
{% if field.type %}
  - `type` {{ field.type }}
{% endif %}
{% if field.constraints %}
  - `constraints`:
  {% for key, value in field.constraints.items() if value %}
    {% if key == 'pattern' %}
    - `{{ key }}` `{{ value }}`
    {% else %}
    - `{{ key }}` {{ value }}
    {% endif %}
  {% endfor %}
{% endif %}
```

Since the package template includes the resource template, which in turn includes the field template, rendering the package template renders the whole stack.

```py
render_template("package.md", {"package": descriptor})
```

# `package`


## `main`

  - `schema`
    - `primaryKey` ['id']

### `id`

  - `description` Any positive integer
  - `type` integer
  - `constraints`:
    - `minimum` 1

### `integer_minmax`

  - `description` An integer between 1 and 10
  - `type` integer
  - `constraints`:
    - `minimum` 1
    - `maximum` 10

### `number_min`

  - `description` Any number >= 0
  - `type` number
  - `constraints`:

### `boolean`

  - `description` Any boolean
  - `type` boolean

### `string_minmax`

  - `description` Any string with length between 2 and 3
  - `type` string
  - `constraints`:
    - `minLength` 2
    - `maxLength` 3

### `string_enum`

  - `description` One of the first three letters of the alphabet
  - `type` string
  - `constraints`:
    - `enum` ['a', 'b', 'c']


## `secondary`

  - `schema`
    - `foreignKeys`
      - [1]
        - `fields` ['main_id']
        - `reference`
          - `resource` main
          - `fields` ['id']

### `main_id`

  - `description` Any value in main.id
  - `type` integer

### `string`

  - `description` Any string of up to 3 characters
  - `type` string
  - `constraints`:
    - `maxLength` 3

### Jinja templates (with tables)

Alternatively, we could represent fields in a table. Here is an example of that:

`resource-table.md`

```jinja
## `{{ resource.name }}`{% if resource.title %} {{ resource.title }}{% endif %}
{{ '\n' }}
{% if resource.description %}
  - `description` {{ resource.description | indent(4, False) }}
{% endif %}
{% if resource.path %}
  - `path` {{ resource.path }}
{% endif %}
{% if resource.schema %}
  - `schema`
{{ resource.schema | filter_dict(exclude=['fields']) | dict_to_markdown(level=2) }}
{% endif %}

{{ resource.schema.fields | tabulate() }}
```

It could be improved by further rendering the constraints (probably in a pre-processing step that converts all the constraints for a field to a single string), but you get the idea.

```py
curator.util.render_template("resource-table.md", {"resource": descriptor['resources'][0]})
```

## `main`

  - `schema`
    - `primaryKey` ['id']

| name           | description                                    | type    | constraints                      |
|:---------------|:-----------------------------------------------|:--------|:---------------------------------|
| id             | Any positive integer                           | integer | {'minimum': 1}                   |
| integer_minmax | An integer between 1 and 10                    | integer | {'minimum': 1, 'maximum': 10}    |
| number_min     | Any number >= 0                                | number  | {'minimum': 0}                   |
| boolean        | Any boolean                                    | boolean |                                  |
| string_minmax  | Any string with length between 2 and 3         | string  | {'minLength': 2, 'maxLength': 3} |
| string_enum    | One of the first three letters of the alphabet | string  | {'enum': ['a', 'b', 'c']}        |

**Comment by roll** [comment]
@ezwelty 
It looks great!

I think we will finish this issue soon with this joint effort

**Comment by XachaB** [comment]
Thanks for working on this, I think this could be very useful !

I am wondering whether a more textual representation could be considered for the markdown. The markdown rendition is not intended to be parsed again to convert back to json or yaml, but instead, to be read by humans. So I think it is possible to be more implicit instead of translating all of the json structure. For example, I think that in a documentation site, the following:

---------
- `id` (integer): Any positive integer. Minimum 1. 
------------

is easier to read than:

----------
### `id`
 
 * `description` Any positive integer
 * `type` integer
* `constraints`:
    * `minimum` 1

---------

That would be something like 

~~~
- `{{ field.name }}`{% if field.title %} **{{ field.title }}**{% endif %}{% if field.type %} 
({{ field.type }}){% endif %}: 
{% if field.description %} {{ field.description }}{% endif %}. 
{% if field.constraints %}{% for key, value in field.constraints.items() if value %} 
{{ key }} `{{ value }}`.{% endfor %}{% endif %}
~~~

**Comment by ezwelty** [comment]
@XachaB Certainly, but some might prefer to keep it DRY (don't repeat yourself) and not repeat field constraints and type again in the description. In which case, these would need to be processed into a human-readable string, and this can be done in many different ways.

It isn't possible to please everyone, so perhaps `frictionless-py` could include 1-2 default JInja templates (for convenience), and the ability to provide custom templates.

**Comment by shashigharti** [comment]
Hi @roll For this, I plan to use the solution shared by @ezwelty as starting point. Looking for your suggestion!

**Comment by roll** [comment]
Great @shashigharti, I like using `jinja2` as it's out standard templating language (e.g. also used in Livemark). Also, it's good that we can build on top of this issue thread work :+1:

**Comment by ezwelty** [comment]
@shashigharti FYI, there was a small indent bug in my original `json_to_markdown` function.

```python
def json_to_markdown(
    x: Union[dict, list, int, float, str, bool],
    level: int = 0,
    tab: int = 2,
    flatten_scalar_lists: bool = True,
) -> str:
    """Render any JSON-like object as Markdown, using nested bulleted lists."""

    def _scalar_list(x) -> bool:
        return isinstance(x, list) and all(not isinstance(xi, (dict, list)) for xi in x)

    def _iter(x: Union[dict, list, int, float, str, bool], level: int = 0) -> str:
        if isinstance(x, (dict, list)):
            if isinstance(x, dict):
                labels = [f"- `{key}`" for key in x]
            elif isinstance(x, list):
                labels = [f"- [{i + 1}]" for i in range(len(x))]
            values = x if isinstance(x, list) else list(x.values())
            if isinstance(x, list) and flatten_scalar_lists:
                scalar = [not isinstance(value, (dict, list)) for value in values]
                if all(scalar):
                    values = [f"{values}"]
            lines = []
            for label, value in zip(labels, values):
                if isinstance(value, (dict, list)) and (
                    not flatten_scalar_lists or not _scalar_list(value)
                ):
                    lines.append(f"{label}\n{_iter(value, level=level + 1)}")
                else:
                    if isinstance(value, str):
                        # Indent to align following lines with '- '
                        value = jinja2.filters.do_indent(value, width=2, first=False)
                    lines.append(f"{label} {value}")
            txt = "\n".join(lines)
        else:
            txt = str(x)
        if level > 0:
            txt = jinja2.filters.do_indent(txt, width=tab, first=True, blank=False)
        return txt

    return jinja2.filters.do_indent(
        _iter(x, level=0), width=tab * level, first=True, blank=False
    )
```

I also found it was more reliable to initiate the `jinja2.FileSystemLoader` based on the directory of the template file passed to the `render_template` function, like this:

```python
def render_template(path: str, data: dict) -> str:
    dir = os.path.dirname(os.path.abspath(path))
    file = os.path.split(path)[1]
    environment = RelativeEnvironment(
        loader=jinja2.FileSystemLoader(dir), lstrip_blocks=True, trim_blocks=True
    )
    environment.filters["filter_dict"] = filter_dict
    environment.filters["dict_to_markdown"] = json_to_markdown
    environment.filters["tabulate"] = dicts_to_markdown_table
    template = environment.get_template(file)
    return template.render(**data)
``````

**Comment by shashigharti** [comment]
Thank you! @ezwelty

**Comment by johanricher** [comment]
Nice, can't wait to use that feature! Thank you so much @shashigharti for this remarkable contribution, and of course @roll for all your continuous work. :clap:

**Comment by roll** [comment]
And of course, thanks to @ezwelty :+1:

**Comment by dennisangemi** [comment]
Fantastic work! Is there a way to access this function via cli? If yes, could you link me some docs please?

I've done [this](https://github.com/chiaraadornetto/dati-tv-elezioni-ue-2019#readme) manually lol

cc @roll

**Comment by roll** [comment]
Thanks for the suggestion -- I've added a feature request for it

**Comment by dennisangemi** [comment]
> Thanks for the suggestion -- I've added a feature request for it

Wow! Thx ;)
