### ISSUE TITLE
Take into account basepath for describe 

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#873]
# Overview

As a user, I want to create a data package from my root project directory and then save it e.g. to a data directory. Currently, providing a basepath to `describe` doesn't change the paths inside the package (still from the root).

```bash
frictionless describe --basepath data 'data/*.csv' > data/package.json
# will create a package with paths relative to a root dir
```

**Comment by mor120** [comment]
Hey @roll,
I would like to take this issue and fix it as my first contribution to an open-source project.
Before I do, I want to make sure I understand the issue correctly.

Let's say I have a directory that looks like that:
```
+ my dir
    + data
        - capital-3.csv
        - country-3.csv
```
On the terminal I am on **my_dir** directory and execute the command:
``` ...\my_dir>frictionless describe --basepath data data/*.csv > data/package.json```

and now we got an output file that named **package.json** under **data** directory.
```
+ my dir
    + data
        - capital-3.csv
        - country-3.csv
        - package.json
```

The issue here is that the output of the **path** row does include the path from the root directory (**my_dir**) and not from the new root (**data**) of the file.


```
# --------
# metadata: data/*.csv
# --------

profile: data-package
resources:
    .
    .
    path: data\capital-3.csv
    .
    .
```

And should be like that:
```path: capital-3.csv```



Is that correct?

**Comment by roll** [comment]
Hi @mor120!

Thanks for looking at it. 

Your task definition is perfectly correct. The bug itself is not related to CLI and, I think, can be resolved in `package/resource.infer` functions. So the tests to check it also might be written for these classes.

I'm assigning you to communicate that you're working on it :+1:

**Comment by mor120** [comment]
Hey again,
I'm on it :)

**Comment by mor120** [comment]
Hey @roll,

It seems like the issue is only on the CLI, and this is why I think so:

I've created and ran a file with the following content:

```Python
from pprint import pprint
from frictionless import describe

package = describe("*.csv", basepath="data")

pprint(package)
```

and got the following as output:

```
{'profile': 'data-package',
 'resources': [{'encoding': 'utf-8',
                'format': 'csv',
                'hashing': 'md5',
                'name': 'capital-3',
                'path': 'capital-3.csv',
                'profile': 'tabular-data-resource',
                'schema': {'fields': [{'name': 'id', 'type': 'integer'},
                                      {'name': 'name', 'type': 'string'}]},
                'scheme': 'file'},
               {'encoding': 'utf-8',
                'format': 'csv',
                'hashing': 'md5',
                'name': 'country-3',
                'path': 'country-3.csv',
                'profile': 'tabular-data-resource',
                'schema': {'fields': [{'name': 'id', 'type': 'integer'},
                                      {'name': 'capital_id', 'type': 'integer'},
                                      {'name': 'name', 'type': 'string'},
                                      {'name': 'population',
                                       'type': 'integer'}]},
                'scheme': 'file'}]}
```

As you can see,
The **path** does not include the **basepath**, which is in that case is the **data** folder.
I also get the same result when exporting by adding the line to the .py file:
```
package.to_json("data/country.json")
```

What do you think?
I tried to create the problem again but instead of using the CLI, I used a python file.


Is that only a problem that occurs when using the CLI?
If it is, I would like to have a clue of where the files I'm looking for in order to fix it :)

Thanks.

**Comment by mor120** [comment]
Hey @roll,

I found the bug under program/desribe.py.

I have created a PR - #875
