### ISSUE TITLE
Package validation doesn't support non-object resource schema

### ISSUE THREAD

**Issue by niconoe** [frictionlessdata/frictionless-py#935]
# Overview

According to the documentation (https://specs.frictionlessdata.io/data-resource/#resource-schemas): 

> The value for the schema property on a resource MUST be an object representing the schema OR a string that identifies the location of the schema.

> If a string it must be a url-or-path as defined above, that is a fully qualified http URL or a relative POSIX path. The file at the location specified by this url-or-path string MUST be a JSON document containing the schema.

I have a package where resources schemas are specified as URLs:
```
{
      "name": "deployments",
      "path": "deployments.csv",
      "profile": "tabular-data-resource",
      "format": "csv",
      "mediatype": "text/csv",
      "encoding": "utf-8",
      "schema": "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.6/deployments-table-schema.json"
    },
```

Unfortunately, I cannot validate the package because `frictionless-py` requires `schema` to be an object:

The code:

```
import json
from pprint import pprint
from frictionless import validate_package

with open("example/datapackage.json") as json_file:
  descriptor_data = json.load(json_file)

  report = validate_package(descriptor_data)
    for err in report.errors:  # report.valid is False
      pprint(err)
```

The result:

```
{'code': 'package-error',
 'description': 'A validation cannot be processed.',
 'message': 'The data package has an error: '
            '"\'https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.6/deployments-table-schema.json\' '
            'is not of type \'object\'" at "resources/0/schema" in metadata '
            'and at '
            '"allOf/0/properties/resources/items/properties/schema/type" in '
            'profile',
 'name': 'Package Error',
 'note': '"\'https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.6/deployments-table-schema.json\' '
         'is not of type \'object\'" at "resources/0/schema" in metadata and '
         'at "allOf/0/properties/resources/items/properties/schema/type" in '
         'profile',
 'tags': []}
```

Thanks for your help!

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by fjuniorr** [comment]
Hi @niconoe!

Which version of `frictionless-py` are you using? 

I think this was fixed in PR #927 that was shipped in v4.19.2

**Comment by niconoe** [comment]
Thanks @fjuniorr!

I'm using v4.19.5

**Comment by roll** [comment]
Hi @niconoe,

Can you please share the package you're validating?

**Comment by roll** [comment]
I think the problem is here - https://github.com/tdwg/camtrap-dp/blob/main/camtrap-dp-profile.json#L36. The custom profile doesn't let the `schema` property be a string.

Closing for now, as it seems to be not related to the framework itself.

Please let me know if it didn't help.

**Comment by peterdesmet** [comment]
Hi @roll, I would like to reopen this issue. I did not encounter this issue with older versions of frictionless (v4.18.2) and the bug is not related to the custom profile. I've created a [minimal example](https://gist.github.com/peterdesmet/a5bb89fcfb930ad08e53175942ace50e):

1. When I use `"profile": "data-package"` in my `datapackage.json` then the validation works fine, **even when using a path** (rather than a verbose object) in resource `schema`. 
2. When I use `"profile": "https://specs.frictionlessdata.io/schemas/data-package.json"` then the validation fails, saying that the schemas should be an object (and not a path string):

>  The data package has an error: "'species-table-schema.json' is not of type 'object'" at "resources/0/schema" in metadata and at "allOf/0/properties/resources/items/properties/schema/type" in profile

Why the different behaviour? Note also that according to the specs, both path and object are allowed, but that the [JSON schema](https://specs.frictionlessdata.io/schemas/data-package.json) has `"schema": { "type": "object"` } not `"type": ["string", "object"]`
