### ISSUE TITLE
Create summarized view of a Package's Resources

### ISSUE THREAD

**Issue by lucas-wave** [frictionlessdata/frictionless-py#980]
# Overview

I've been toying around with using frictionless for schema inference on batches of files (a data package in frictionless terminology). While the utility is useful in that it can infer the schema for each file in the batch / resource in the package, it'd help my workflow to be able to view a single, summarized view of all the resources in a package.

I'm imagining functionality that would, for example, look at all the resources and find the _most common_ resource representation of the collection of resources, or identify all the _shared values_ of the resources (i.e. all resources share an encoding and a set of 2 fields).

Ultimately, I think this approach could prove useful for detecting outlier resources in a package - for example, finding the subset of resources that _don't_ share an otherwise uniform schema.

**Comment by roll** [comment]
Hi @lucas-wave, nice idea, and work!

If we want to merge into core instead of providing some extension I think it would be better to create a separate API for this logic. For example, a `Comparator` class that will include all the proposed logic and will be providing related services. Also, we can add `frictionless compare` CLI command. In the beginning, it can be marked as an experimental interface.

Currently, we're working on cleaning up the framework trying to optimize main usage paths like validation for performance and maintainability etc. So we try avoiding complicating any of existing parts of the framework ATM.

**Comment by lucas-wave** [comment]
Thanks for the feedback and guidance here! I'll close this one out and take another stab at it using the `Comparator`class.
