### ISSUE TITLE
Validating Packages stops too early

### ISSUE THREAD

**Issue by enioarz** [frictionlessdata/frictionless-py#999]
Hello, I have been testing using the tool for a medium sized project and one thing that has been bothering me is that when I try to validate a data package with the CLI it stops the report at the first file it does not find from the schema. I think it would be a nice feature to get feedback on all the files that are not found, because in larger collections it can get tiresome iterating through the tool trying to figure out what its missing in a package.

This is the error I get usually:

scheme-error  The data source could not be successfully loaded: [Errno 2] No such file or directory: 'my_missing_file.csv'

**Comment by roll** [comment]
Thanks! We will investigate

**Comment by aivuk** [comment]
@Eugenio2192 currently if you have a package with multiple resources, the test don't stop when it fails in some resources, it test all resources and provide information at the end of what failed and what didn't like in the example below:

```
 -------
# invalid: capital-invalidaaaa.csv
# -------

===  =====  ============  ================================================================================================================
row  field  code          message                                                                                                         
===  =====  ============  ================================================================================================================
            scheme-error  The data source could not be successfully loaded: [Errno 2] No such file or directory: 'capital-invalidaaaa.csv'
===  =====  ============  ================================================================================================================


# -----
# valid: capital-valid.csv
# -----

# -----
# valid: table.csv
# -----
```
Can you provide more details of your case? The example above I created a datapackage with 3 resources, with the first one failing because the resource file didn't exist and validate it with:

`frictionless validate capital.package.yaml  --type package`

**Comment by enioarz** [comment]
Thanks for the feedback I just discovered I have an older version of the software, I think the reason was that I used the packaged version from conda-forge. I reinstalled with pip and the issue was solved. The version in conda-forge for windows is 4.17.
